# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtnEncuestas.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_Encuestas(object):
    def setupUi(self, Encuestas):
        if not Encuestas.objectName():
            Encuestas.setObjectName(u"Encuestas")
        Encuestas.resize(717, 570)
        self.centralwidget = QWidget(Encuestas)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbSistemadegestiondeencuestas = QLabel(self.centralwidget)
        self.lbSistemadegestiondeencuestas.setObjectName(u"lbSistemadegestiondeencuestas")
        self.lbSistemadegestiondeencuestas.setGeometry(QRect(150, 0, 371, 41))
        font = QFont()
        font.setFamilies([u"Arial Black"])
        font.setPointSize(12)
        font.setBold(True)
        self.lbSistemadegestiondeencuestas.setFont(font)
        self.lbpregunta_2 = QLabel(self.centralwidget)
        self.lbpregunta_2.setObjectName(u"lbpregunta_2")
        self.lbpregunta_2.setGeometry(QRect(10, 250, 291, 16))
        font1 = QFont()
        font1.setFamilies([u"Arial Black"])
        font1.setPointSize(10)
        font1.setBold(True)
        self.lbpregunta_2.setFont(font1)
        self.lbpregunta_3 = QLabel(self.centralwidget)
        self.lbpregunta_3.setObjectName(u"lbpregunta_3")
        self.lbpregunta_3.setGeometry(QRect(10, 280, 291, 16))
        self.lbpregunta_3.setFont(font1)
        self.txtpregunta_2 = QLineEdit(self.centralwidget)
        self.txtpregunta_2.setObjectName(u"txtpregunta_2")
        self.txtpregunta_2.setGeometry(QRect(310, 250, 165, 22))
        font2 = QFont()
        font2.setFamilies([u"Arial Black"])
        font2.setPointSize(12)
        self.txtpregunta_2.setFont(font2)
        self.txtpregunta_2.setMaxLength(50)
        self.txtpregunta_3 = QLineEdit(self.centralwidget)
        self.txtpregunta_3.setObjectName(u"txtpregunta_3")
        self.txtpregunta_3.setGeometry(QRect(310, 280, 165, 22))
        self.txtpregunta_3.setFont(font2)
        self.txtpregunta_3.setMaxLength(50)
        self.lbpregunta_1 = QLabel(self.centralwidget)
        self.lbpregunta_1.setObjectName(u"lbpregunta_1")
        self.lbpregunta_1.setGeometry(QRect(10, 220, 291, 16))
        self.lbpregunta_1.setFont(font1)
        self.lbfecha = QLabel(self.centralwidget)
        self.lbfecha.setObjectName(u"lbfecha")
        self.lbfecha.setGeometry(QRect(20, 310, 171, 17))
        self.lbfecha.setFont(font)
        self.lbtipo = QLabel(self.centralwidget)
        self.lbtipo.setObjectName(u"lbtipo")
        self.lbtipo.setGeometry(QRect(10, 104, 161, 17))
        self.lbtipo.setFont(font)
        self.lbnombre = QLabel(self.centralwidget)
        self.lbnombre.setObjectName(u"lbnombre")
        self.lbnombre.setGeometry(QRect(10, 76, 181, 17))
        self.lbnombre.setFont(font)
        self.lbtelefono = QLabel(self.centralwidget)
        self.lbtelefono.setObjectName(u"lbtelefono")
        self.lbtelefono.setGeometry(QRect(10, 187, 91, 17))
        self.lbtelefono.setFont(font)
        self.lbcorreo = QLabel(self.centralwidget)
        self.lbcorreo.setObjectName(u"lbcorreo")
        self.lbcorreo.setGeometry(QRect(10, 159, 81, 17))
        self.lbcorreo.setFont(font)
        self.lbcodigo = QLabel(self.centralwidget)
        self.lbcodigo.setObjectName(u"lbcodigo")
        self.lbcodigo.setGeometry(QRect(10, 130, 81, 17))
        self.lbcodigo.setFont(font)
        self.txtpregunta_1 = QLineEdit(self.centralwidget)
        self.txtpregunta_1.setObjectName(u"txtpregunta_1")
        self.txtpregunta_1.setGeometry(QRect(310, 220, 165, 22))
        self.txtpregunta_1.setFont(font2)
        self.txtpregunta_1.setMaxLength(50)
        self.txttelefono = QLineEdit(self.centralwidget)
        self.txttelefono.setObjectName(u"txttelefono")
        self.txttelefono.setGeometry(QRect(110, 189, 165, 22))
        self.txttelefono.setFont(font2)
        self.txttelefono.setMaxLength(7)
        self.txtnombre = QLineEdit(self.centralwidget)
        self.txtnombre.setObjectName(u"txtnombre")
        self.txtnombre.setGeometry(QRect(190, 70, 165, 22))
        self.txtnombre.setFont(font2)
        self.txtnombre.setMaxLength(50)
        self.txtfecha = QLineEdit(self.centralwidget)
        self.txtfecha.setObjectName(u"txtfecha")
        self.txtfecha.setGeometry(QRect(190, 310, 165, 22))
        self.txtfecha.setFont(font2)
        self.txtfecha.setMaxLength(50)
        self.cbtipo = QComboBox(self.centralwidget)
        self.cbtipo.addItem("")
        self.cbtipo.addItem("")
        self.cbtipo.addItem("")
        self.cbtipo.addItem("")
        self.cbtipo.setObjectName(u"cbtipo")
        self.cbtipo.setGeometry(QRect(170, 100, 170, 22))
        self.cbtipo.setFont(font2)
        self.txtcodigo = QLineEdit(self.centralwidget)
        self.txtcodigo.setObjectName(u"txtcodigo")
        self.txtcodigo.setGeometry(QRect(110, 131, 165, 22))
        self.txtcodigo.setFont(font2)
        self.txtcodigo.setMaxLength(10)
        self.txtcorreo = QLineEdit(self.centralwidget)
        self.txtcorreo.setObjectName(u"txtcorreo")
        self.txtcorreo.setGeometry(QRect(110, 160, 165, 22))
        self.txtcorreo.setFont(font2)
        self.txtcorreo.setMaxLength(50)
        self.btnguardar = QPushButton(self.centralwidget)
        self.btnguardar.setObjectName(u"btnguardar")
        self.btnguardar.setGeometry(QRect(10, 350, 91, 31))
        self.btnguardar.setFont(font)
        self.btnborrar = QPushButton(self.centralwidget)
        self.btnborrar.setObjectName(u"btnborrar")
        self.btnborrar.setGeometry(QRect(110, 350, 81, 31))
        self.btnborrar.setFont(font)
        self.btnactualizar = QPushButton(self.centralwidget)
        self.btnactualizar.setObjectName(u"btnactualizar")
        self.btnactualizar.setGeometry(QRect(200, 350, 101, 31))
        self.btnactualizar.setFont(font)
        self.btnlimpiar = QPushButton(self.centralwidget)
        self.btnlimpiar.setObjectName(u"btnlimpiar")
        self.btnlimpiar.setGeometry(QRect(310, 350, 91, 31))
        self.btnlimpiar.setFont(font)
        self.txtbuscarencuesta = QLineEdit(self.centralwidget)
        self.txtbuscarencuesta.setObjectName(u"txtbuscarencuesta")
        self.txtbuscarencuesta.setGeometry(QRect(300, 40, 108, 23))
        font3 = QFont()
        font3.setFamilies([u"Arial Black"])
        self.txtbuscarencuesta.setFont(font3)
        self.txtbuscarencuesta.setMaxLength(10)
        self.lbbuscarporcodigoencuesta = QLabel(self.centralwidget)
        self.lbbuscarporcodigoencuesta.setObjectName(u"lbbuscarporcodigoencuesta")
        self.lbbuscarporcodigoencuesta.setGeometry(QRect(10, 40, 291, 31))
        self.lbbuscarporcodigoencuesta.setFont(font)
        self.btnbuscar = QPushButton(self.centralwidget)
        self.btnbuscar.setObjectName(u"btnbuscar")
        self.btnbuscar.setGeometry(QRect(420, 40, 111, 23))
        self.btnbuscar.setFont(font)
        icon = QIcon()
        iconThemeName = u"system-search"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u"Proveedores/src/UI", QSize(), QIcon.Mode.Normal, QIcon.State.Off)

        self.btnbuscar.setIcon(icon)
        Encuestas.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Encuestas)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 717, 21))
        Encuestas.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Encuestas)
        self.statusbar.setObjectName(u"statusbar")
        Encuestas.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txtnombre, self.cbtipo)
        QWidget.setTabOrder(self.cbtipo, self.txtcodigo)
        QWidget.setTabOrder(self.txtcodigo, self.txtcorreo)
        QWidget.setTabOrder(self.txtcorreo, self.txttelefono)
        QWidget.setTabOrder(self.txttelefono, self.txtpregunta_1)
        QWidget.setTabOrder(self.txtpregunta_1, self.txtfecha)
        QWidget.setTabOrder(self.txtfecha, self.btnguardar)
        QWidget.setTabOrder(self.btnguardar, self.btnborrar)
        QWidget.setTabOrder(self.btnborrar, self.btnactualizar)
        QWidget.setTabOrder(self.btnactualizar, self.btnlimpiar)

        self.retranslateUi(Encuestas)

        QMetaObject.connectSlotsByName(Encuestas)
    # setupUi

    def retranslateUi(self, Encuestas):
        Encuestas.setWindowTitle(QCoreApplication.translate("Encuestas", u"Sistema de Encuestas de Satisfacci\u00f3n del Cliente", None))
        self.lbSistemadegestiondeencuestas.setText(QCoreApplication.translate("Encuestas", u"SISTEMA DE GESTI\u00d3N DE ENCUESTAS", None))
        self.lbpregunta_2.setText(QCoreApplication.translate("Encuestas", u"Pregunta 2: \u00bfRecomendar\u00eda el servicio?", None))
        self.lbpregunta_3.setText(QCoreApplication.translate("Encuestas", u"Pregunta 3: \u00bfVolver\u00eda a usar\u00a0el\u00a0servicio?", None))
        self.txtpregunta_2.setText("")
        self.txtpregunta_3.setText("")
        self.lbpregunta_1.setText(QCoreApplication.translate("Encuestas", u"Pregunta 1: \u00bfC\u00f3mo califica la atenci\u00f3n? ", None))
        self.lbfecha.setText(QCoreApplication.translate("Encuestas", u"Fecha de registro:", None))
        self.lbtipo.setText(QCoreApplication.translate("Encuestas", u"Tipo de Servicio:", None))
        self.lbnombre.setText(QCoreApplication.translate("Encuestas", u"Nombre del Cliente:", None))
        self.lbtelefono.setText(QCoreApplication.translate("Encuestas", u"Tel\u00e9fono:", None))
        self.lbcorreo.setText(QCoreApplication.translate("Encuestas", u"Correo:", None))
        self.lbcodigo.setText(QCoreApplication.translate("Encuestas", u"C\u00f3digo:", None))
        self.txtpregunta_1.setText("")
        self.cbtipo.setItemText(0, QCoreApplication.translate("Encuestas", u"Seleccionar", None))
        self.cbtipo.setItemText(1, QCoreApplication.translate("Encuestas", u"Presencial", None))
        self.cbtipo.setItemText(2, QCoreApplication.translate("Encuestas", u"Virtual", None))
        self.cbtipo.setItemText(3, QCoreApplication.translate("Encuestas", u"Mixto", None))

        self.btnguardar.setText(QCoreApplication.translate("Encuestas", u"Guardar", None))
        self.btnborrar.setText(QCoreApplication.translate("Encuestas", u"Borrar", None))
        self.btnactualizar.setText(QCoreApplication.translate("Encuestas", u"Actualizar", None))
        self.btnlimpiar.setText(QCoreApplication.translate("Encuestas", u"Limpiar", None))
        self.lbbuscarporcodigoencuesta.setText(QCoreApplication.translate("Encuestas", u"Buscar por C\u00f3digo de Encuesta", None))
        self.btnbuscar.setText(QCoreApplication.translate("Encuestas", u"Buscar", None))
    # retranslateUi

